//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Triario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int id_num { get; set; }
        public int CC { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string EUser { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string Fk_Department { get; set; }
    
        public virtual Department Department { get; set; }

        public string FullName => $"{FName} {LName}";
    }
}
